### ISSUE TITLE
`delay` function from Modelica

### ISSUE THREAD

**Issue by ricfrod** [SciML/ModelingToolkit.jl#1010]
Hello! I couldn't find any documentation regarding time-delayed variables such as the ones produced by Modelica's `delay` function, so I was wondering if there is any intention of such an implementation in the future?

I know for instance that Modia.jl has an [open issue](https://github.com/ModiaSim/Modia.jl/issues/44) for this very idea, but maybe that functionality is being left for their 1.0 release.

Thanks in advance!

**Comment by ChrisRackauckas** [comment]
This is a duplicate of https://github.com/SciML/ModelingToolkit.jl/issues/955, it will just be `x(t-1)` since we have a full set of Delay Differential Equation solvers so all of the issues referenced in https://build.openmodelica.org/Documentation/ModelicaReference.Operators.%27delay()%27.html are solved numerically already.

**Comment by ricfrod** [comment]
Ok, thank you!
