### ISSUE TITLE
Composition vs inheritance

### ISSUE THREAD

**Issue by YingboMa** [SciML/ModelingToolkit.jl#1052]
When composing models, we need to namespace the variables, so that `x ~ sys.x` becomes something like `x ~ sys₊x`. Note that from this example, we can see that `sys.x` _**CANNOT**_ be equal to `x`, because `x ~ x` would be a redundant equation.

On the other hand, when doing inheritance, we don't want to namespace the variables, so we can simply adding more equations into the original components. Note that in the absence of namespacing, i.e. making `sys.x` equal to `x`, `x ~ sys.x` will be an illegal equation, as it's just saying `x ~ x`.
```julia
julia> eq = @nonamespace x ~ sys.x
x(t) ~ x(t)

julia> 0 ~ eq.lhs - eq.rhs
ERROR: MethodError: no method matching ~(::Int64, ::Int64)
```

The behavior of `sys.x` also seems to confuse a lot of people, as it does composition automatically, which means that `x` is not equal to `sys.x`. Maybe the default behavior should be doing inheritance, and we should redesign the way that we do composition. My proposed syntax is:

Composition:
```julia
@namespace eqs = [sys1.x ~ sys2.x] # getproperty(sys1, :x; namespace=true) ~ getproperty(sys2, :x; namespace=true)
@named newsys = compose_system(sys1, sys2, eqs)
isequal(newsys.sys1, sys1)
isequal(newsys.sys1.x, sys1₊x) # so, `newsys.sys1.x` should be interpreted as `newsys."sys1.x"`
isequal(newsys.sys2.x, sys2₊x)
isequal(equations(newsys), [sys1₊x ~ sys2₊x])
```

Inheritance:
```julia
eqs = [sys1.x ~ sin(t)]
@named newsys = inheritance(sys1, sys2, eqs)
isequal(equations(newsys), [equations(sys1); equations(sys2); eqs])
```

Another common complain is the printing of `sys1₊x`. I think we should explicitly have an object that's in the form of `Namespace(sys, x)` instead of denoting namespacing by naming convention. This should completely avoid the possibility of accidental variable collision as well. Moreover, we can overload `show` methods on `Namespace`, so that the pretty printing is `sys1₊x` (or something else), while `show(newsys.sys1.x)` prints `Namespace(sys, x)`. This will make namespaced objects copy-paste-able as well. Though, the draw back is that `Namespace` may introduce many edge cases in the current code due to various assumptions on the variable naming convention and such.

This issue covers the underlying problem of: #1049 #907 #807 #902 #971 #832 #722

CC: @ChrisRackauckas @shashi

**Comment by ChrisRackauckas** [comment]
This has nothing to do with composition vs inheritance. I think the reason why it's not connecting is because the examples that you're looking at are not related to why users are asking this question. It arises when trying to refer to the states of a model defined in someone else's module (or package). Take a look at this benchmark code:

https://benchmarks.sciml.ai/html/Jumps/Mendes_multistate_example.html

The model is imported from the problem library, but there's this curious line:

```julia
@variables t S7(t) S8(t) S9(t)
```

why is that being done? Well, one needs to `sol[S7]` to get the value, but `S7` is defined... nowhere! So right now the "correct" solution is to grab ModelingToolkit (a library that the user has not interacted with BTW, they are a "Catalyst user", just using the DSL macro), and define a few variables, in order to then grab the variable from the solution. That in some sense is a leaky abstraction: it requires every downstream DSL to require its users to use MTK directly.

The reason for this is because, while someone defines S7(t), it's not the user, it's the macro. That all gets cleaned up so now there's no reference to it. How can you get it? In theory you can do `findfirst(isequal(sym),rn.states)` if you know the `sym` of it correct, but then you need to know the whole `var"S7(t)"` conventions, etc. That's not intuitive and not a real solution. The natural thing that everyone gravitates towards is `rn.S7`, or `model.S7`, etc. I can see why that intuitively makes sense: that symbol is defined in the model, give it to me. A similar thing happens in the Modelica StdLib: `sol[...]`? How do you access the variables of the model from the solution? Right now the solution is to `@variables match_the_name(t)`, and then `.` from there. It's rather weird.

I think the reason that people are drawn to this form is because it matches namespacing in Julia. If you think of a model as a module, self-referential drops the reference. For example, `Main.x == x`. In some sense users are trying to say "give me the variable from this model, because that system is the only place I know where it's defined", just like how you'd grab a variable or function from some module. However, the issue then arises that referencing the variable from outside the namespace is different from referring to it from within the namespace, which is different from Julia's module system and leads to the unfortunate issue that there is no way to actually refer to variables from outside the namespace 🤷. So you just create a new one that mirrors it and rely on symbol name equality, which falls apart if the symbol is not match the default type. That's... not good.

So what could we do about this? I think the solution is just to special case self-reference. I.e. for `model.x`, if `x in get_states(model)`, then `isequal(model.x,x)`. The other case would be `model.subsys.x`, which users would want `sol[model.subsys.x]` to plot `sol[subsys.x]`. I think this can be done by special casing the highest level index. The `getproperty` overload of `model` could see if `x in get_states(model)` and remove the reference (just like `Main.x == x`), and then when we recurse `getproperty` we can have a variable `toplevel` which is only true at first, and false in the recursion, since otherwise `model.subsys.x` would simplify back to `x`.

However, that would break the equation building syntax, since now `n.V ~ p.V` simplifies down to `V ~ V`. So I'm a little stumped on the true solution 😅. My current idea is to special case it in the `sol[sys.x]` stage, and I can't quite foresee what issues the user will run into with that, but maybe @baggepinnen has a case beyond plotting/indexing where this shows up.

**Comment by YingboMa** [comment]
The `sol[sys.x]` case can be fixed by declaring some model to be "final", so the default behavior turns into inheritance.

There are still issues with how we are doing composition, though. Like only use a naming convention to enforce namespacing, and `!isequal(sys.x, x)` is very non-intuitive.

**Comment by YingboMa** [comment]
How about `sys.x` for composition and `@unpack x = sys` for inheritance?

**Comment by ChrisRackauckas** [comment]
`@unpack` would conflict with other packages.

**Comment by YingboMa** [comment]
What do you mean by that?

**Comment by YingboMa** [comment]
Example code:
```julia
using ModelingToolkit, OrdinaryDiffEq

@parameters t
@connector function Pin(;name)
    sts = @variables v(t)=1.0 i(t)=1.0
    ODESystem(Equation[], t, sts, []; name=name)
end

function ModelingToolkit.connect(::Type{Pin}, ps...)
    eqs = [
           0 ~ sum(p->p.i, ps) # KCL
          ]
    # KVL
    for i in 1:length(ps)-1
        push!(eqs, ps[i].v ~ ps[i+1].v)
    end

    return eqs
end

function Ground(;name)
    @named g = Pin()
    eqs = [g.v ~ 0]
    ODESystem(eqs, t, [], [], systems=[g]; name=name)
end

function OnePort(;name)
    @named p = Pin()
    @named n = Pin()
    sts = @variables v(t)=1.0 i(t)=1.0
    eqs = [
           v ~ p.v - n.v
           0 ~ p.i + n.i
           i ~ p.i
          ]
    ODESystem(eqs, t, sts, [], systems=[p, n]; name=name)
end

function ConstantVoltage(;name, V = 1.0)
    @named oneport = OnePort()
    @unpack v = oneport
    ps = @parameters V=V
    eqs = [
           V ~ v
          ]
    extend(oneport, ODESystem(eqs, t, [], ps; name=name); name=name)
end

function Resistor(;name, R = 1.0)
    @named oneport = OnePort()
    @unpack v, i = oneport
    ps = @parameters R=R
    eqs = [
           v ~ i * R
          ]
    extend(oneport, ODESystem(eqs, t, [], ps; name=name); name=name)
end

function Capacitor(;name, C = 1.0)
    @named oneport = OnePort()
    @unpack v, i = oneport
    ps = @parameters C=C
    D = Differential(t)
    eqs = [
           D(v) ~ i / C
          ]
    extend(oneport, ODESystem(eqs, t, [], ps; name=name); name=name)
end

R = 1.0
C = 1.0
V = 1.0
@named resistor = Resistor(R=R)
@named capacitor = Capacitor(C=C)
@named source = ConstantVoltage(V=V)
@named ground = Ground()

rc_eqs = [
          connect(source.p, resistor.p)
          connect(resistor.n, capacitor.p)
          connect(capacitor.n, source.n, ground.g)
         ]

@named rc_model = ODESystem(rc_eqs, t, systems=[resistor, capacitor, source, ground])
sys = structural_simplify(rc_model)
u0 = [
      capacitor.v => 0.0
      capacitor.p.i => 0.0
      resistor.v => 0.0
     ]
prob = ODEProblem(sys, u0, (0, 10.0))
sol = solve(prob, Rodas4())
```

**Comment by ChrisRackauckas** [comment]
Parameters.jl unpack is still pretty widely used.

**Comment by YingboMa** [comment]
Parameters.jl just uses UnPack's `@unpack`.

**Comment by ChrisRackauckas** [comment]
Yeah, and we're not using it here right?

**Comment by YingboMa** [comment]
We are using it here. UnPack doesn't call getproperty directly. So using the one-liner
```julia
UnPack.unpack(sys::ModelingToolkit.AbstractSystem, ::Val{p}) where p = getproperty(sys, p; namespace=false)
```
would alter its behavior for only `AbstractSystem`, and no conflict would happen.

**Comment by ChrisRackauckas** [comment]
oh, interesting. Yes, that works.

**Comment by shashi** [comment]
Another syntax we could consider:

```
ODESystem([sys1,sys2,eq1])
```

Does inheritence and

```
ODESystem([eq1,eq2], systems=[sys1,sys2])
```

is composition

This is backwards compatible.

**Comment by YingboMa** [comment]
Then how about states and such? I don't like using `ODESystem` for inheritance as well.

**Comment by shashi** [comment]
States can be forwarded automatically from the inherited system right? 

> I don't like using ODESystem for inheritance as well.

I think

```
ODESystem([sys1,sys2,eq1])
```
is a perfectly good syntax to co-opt for either inheritance or composition.

**Comment by YingboMa** [comment]
I would like states be explicitly stated. Otherwise, it needs to recurse into the equations just to get the states, while users can just pass them directly.

**Comment by YingboMa** [comment]
Also, would it be confusing when `ODESystem([sys1,sys2,eq1])` is inheritance and `ODESystem(eq1,..., systems=[sys1, sy2])` is composition?
