### ISSUE TITLE
Input & output systems

### ISSUE THREAD

**Issue by YingboMa** [SciML/ModelingToolkit.jl#1111]
From the discussion with @ChrisRackauckas last Friday.

It seems like controls are a subproblem of input and output systems. The outputs of controllers are inputs of original systems, while closed-loop control can be handled by inputs of the controllers as well. Various matrices relevant for linearization can be formulated in this language as well.

**Comment by cadojo** [comment]
Does this mean that the `control` syntax introduced in #1059 should be replaced with subsystems?

**Comment by YingboMa** [comment]
Yes.

**Comment by cadojo** [comment]
Gotcha. I hope y'all don't mind my commenting on these issues. I'm interested in helping out with features like this – I'm learning a lot by working through `ModelingToolkit` descriptions of systems I've worked on in my studies. 

If a controller is an input-output system by itself, is there a way to specify "no equations", so it's just a pass-through system? I ask because I think there's value in being able to represent a "whole system" (connected inputs, dynamics, and outputs) with symbolic control variables, and symbolic output variables. The only way I see accomplishing this is by writing the input and output subsystems as static gains.

```julia
using ModelingToolkit

# Input "system" (no equations, inputs are passed directly through this sub-system)
@variables δₑ, δₜ # elevator and thrust inputs to a longitudinal aircraft model
inputs = NonlinearSystem(ModelingToolkit.Equation[], [δₑ, δₜ], [])

# Dynamics (the traditional ODE system that describes the longitudinal aircraft dynamics)
@parameters t
@variables x[1:4](t)
d = Differential(t)

"""Multiplies each argument by a random number, and sums the result into a scalar expression."""
random_dynamics(syms::AbstractVector...) = sum(map(x -> rand() * x, collect(syms))
eqs = [
  d(x[1]) ~ randn(4) * transpose(Vector(x)) + randn(2) * transpose([inputs.δₑ, inputs.δₜ]),
  d(x[2]) ~ randn(4) * transpose(Vector(x)) + randn(2) * transpose([inputs.δₑ, inputs.δₜ]),
  d(x[3]) ~ randn(4) * transpose(Vector(x)) + randn(2) * transpose([inputs.δₑ, inputs.δₜ]),
  d(x[4]) ~ randn(4) * transpose(Vector(x)) + randn(2) * transpose([inputs.δₑ, inputs.δₜ]),
]

# Output "system" (let's assume no equations here, the outputs ~are~ the states)
outputs = NonlinearSystem(ModelingToolkit.Equation[], dynamics.x, [])

# system = connect inputs, dynamics, outputs ?

**Comment by lungd** [comment]
This looks very similar to some parts of the project I am working on.
The user can create a "MTKLayer" for (DiffEq)Flux by providing the number of inputs/outputs and a MTK system.

```
function InPin(;name)
  ps = @parameters x=1f0
  ODESystem(Equation[],t,Num[],ps; name)
end

function OutPin(;name)
  vars = @variables x(t)=0f0
  ODESystem(Equation[],t,vars,Num[]; name)
end

function create_pins(in::Integer, out::Integer)
  inpins = [InPin(;name=Symbol("x$(i)_InPin")) for i in 1:in]
  outpins = [OutPin(;name=Symbol("x$(i)_OutPin")) for i in 1:out]
  inpins, outpins
end

function UserDefinedSystem()
  inputs, outputs = create_pins(in, out)
  # create system
  # connect input/output pins with system variables (subsys1.x ~ inputs[1].x, outputs[1].x ~ subsys2.y)
  ODESystem(eqs, t, vars, ps; systems=vcat(inputs,outputs,system))
end
```
The only issue with this approach is the missing adjoint for indexing the solution with a symbol, e.g, `sol[outputs[1].x]`. (https://github.com/SciML/DifferentialEquations.jl/issues/746)
I am not entirely sure if this could become relevant here. Sorry for the noise, if not.

**Comment by dannys4** [comment]
Talked with @ChrisRackauckas and @YingboMa on this today. What we need is to add `input` and `output` states to the systems, then decide how to handle `structural_simplify` and `alias_elimination`. Most importantly, should `structural_simplify` include output states?

**Comment by baggepinnen** [comment]
An output isn't really a state in the traditional sense of the word since it can be computed from other states. I rather think of outputs as functions of the state vector and control inputs, e.g., in the linear case `y = Cx + Du` where `x` is the state and `u` the control input.

Currently, `structural_simplify` removes control outputs
```julia
julia> controls(model)
1-element Vector{Any}:
 u(t)

julia> model = structural_simplify(model)

julia> controls(model)
Any[]
```

**Comment by ChrisRackauckas** [comment]
You can connect a component to an input variable to make it be controlled by parametric functions. I think this can be closed then, but @baggepinnen comment if you think there's anything more to do here.
