### ISSUE TITLE
warning about both MT and Symbolics exporting infimum/supremum

### ISSUE THREAD

**Issue by isaacsas** [SciML/ModelingToolkit.jl#1217]
When I `using Catalyst` I now get the following warning:
```
WARNING: both Symbolics and ModelingToolkit export "infimum"; uses of it in module Catalyst must be qualified
WARNING: both Symbolics and ModelingToolkit export "supremum"; uses of it in module Catalyst must be qualified
```

**Comment by ChrisRackauckas** [comment]
It comes from DomainSets.jl, we need to make sure both are using the same function here 😅

**Comment by tp2750** [comment]
It would be great to fix this.

The functions in [Symbolics.jl](https://github.com/JuliaSymbolics/Symbolics.jl/blob/dacdf070ac7a592ef4a84135d3bf33aa198a1482/src/domains.jl#L18) looks like this:

```julia
function infimum(d::AbstractInterval{T}) where T <: Num
    leftendpoint(d)
end

function supremum(d::AbstractInterval{Num}) where T <: Num
    rightendpoint(d)
end
```

In [DomainSets.jl](https://github.com/JuliaApproximation/DomainSets.jl/blob/64984430e78c97f14294fb1378451ec3e8ffea53/src/generic/domain.jl#L152) like this:

```julia
infimum(d::Domain) = minimum(d)  # if the minimum exists, then it is also the infimum
supremum(d::Domain) = maximum(d)  # if the maximum exists, then it is also the supremum
```
I'm not sure what to do about it though.

**Comment by ChrisRackauckas** [comment]
Looks like this is fixed when using the most recent versions. Let me know if anyone can reproduce this on a recent release of MTK+Symbolics.

**Comment by Neoarroway** [comment]
Julia 1.10.2, try to run the examples on on the Catalyst page. Got the warning instead of picture:


Graph("G", true, "dot", Catalyst.Statement[Catalyst.Node("S", OrderedCollections.OrderedDict{Symbol, Union{Catalyst.Html, String}}(:shape => "circle", :color => "#6C9AC3")), Catalyst.Node("I", OrderedCollections.OrderedDict{Symbol, Union{Catalyst.Html, String}}(:shape => "circle", :color => "#6C9AC3")), Catalyst.Node("R", OrderedCollections.OrderedDict{Symbol, Union{Catalyst.Html, String}}(:shape => "circle", :color => "#6C9AC3")), Catalyst.Node("rx_1", OrderedCollections.OrderedDict{Symbol, Union{Catalyst.Html, String}}(:shape => "point", :color => "#E28F41", :width => ".1")), Catalyst.Node("rx_2", OrderedCollections.OrderedDict{Symbol, Union{Catalyst.Html, String}}(:shape => "point", :color => "#E28F41", :width => ".1")), Catalyst.Edge(Catalyst.NodeID[Catalyst.NodeID("S", "", ""), Catalyst.NodeID("rx_1", "", "")], OrderedCollections.OrderedDict{Symbol, Union{Catalyst.Html, String}}(:label => "1", :labelfontsize => "6")), Catalyst.Edge(Catalyst.NodeID[Catalyst.NodeID("I", "", ""), Catalyst.NodeID("rx_1", "", "")], OrderedCollections.OrderedDict{Symbol, Union{Catalyst.Html, String}}(:label => "1", :labelfontsize => "6")), Catalyst.Edge(Catalyst.NodeID[Catalyst.NodeID("rx_1", "", ""), Catalyst.NodeID("I", "", "")], OrderedCollections.OrderedDict{Symbol, Union{Catalyst.Html, String}}(:label => "2", :labelfontsize => "6")), Catalyst.Edge(Catalyst.NodeID[Catalyst.NodeID("I", "", ""), Catalyst.NodeID("rx_2", "", "")], OrderedCollections.OrderedDict{Symbol, Union{Catalyst.Html, String}}(:label => "1", :labelfontsize => "6")), Catalyst.Edge(Catalyst.NodeID[Catalyst.NodeID("rx_2", "", ""), Catalyst.NodeID("R", "", "")], OrderedCollections.OrderedDict{Symbol, Union{Catalyst.Html, String}}(:label => "1", :labelfontsize => "6"))], OrderedCollections.OrderedDict{Symbol, Union{Catalyst.Html, String}}(:rankdir => "LR"), OrderedCollections.OrderedDict{Symbol, Union{Catalyst.Html, String}}(:shape => "plain", :style => "filled", :color => "white"), OrderedCollections.OrderedDict{Symbol, Union{Catalyst.Html, String}}(:splines => "splines"))
WARNING: both Symbolics and ModelingToolkit export "infimum"; uses of it in module Catalyst must be qualified
WARNING: both Symbolics and ModelingToolkit export "supremum"; uses of it in module Catalyst must be qualified
