### ISSUE TITLE
Detecting Operations that are Variables

### ISSUE THREAD

**Issue by jpfairbanks** [SciML/ModelingToolkit.jl#130]
If i want to write a function that uses an expression in my modeling use case, I need to extract out the variables in the expression, I want to detect these leaves of the expression tree with dispatch and recursion. Unfortunately, compound expressions and variables have the same type of Operation. What is the preferred way to extract the variables of an expression / leaves of the expression tree. 

I'd like to write something like this:
```julia
function apply(expr::Equation, data)
    rhs = expr.rhs
    apply(rhs, data)
end
function apply(expr::Operation, data)
    anses = map(rhs.args) do a
        apply(a, data)
    end
    return rhs.op(anses...)
end
function apply(expr::Variable, data)
    # handle the leave case...
    return getindex(data, expr)
end
```

**Comment by HarrisonGrodin** [comment]
Given an expression like:
```julia
x(t, y(t, u+1))
```
what would you expect the result to be?

**Comment by jpfairbanks** [comment]
I would parse `x` and `y` as functions and so the only leaf nodes are  `t`, `u`, and `1`, with `t` occurring twice. I ended up checking `length(op.args) > 0`.

**Comment by ChrisRackauckas** [comment]
But `x` and `y` may be unknown variables as well (example: this could be describing a PDE)

**Comment by jpfairbanks** [comment]
If a variable depends on some input, is it not best imagined as a function? 

I think that in the `x(t, y(t, u+1))` case we have `x,y` as functions and `t, u` as variables. If you would parse it differently (where `x,y` are variables) what would you call `t,u` to distinguish them? Would you say "primitive variables" or "leaf variables"?

**Comment by ChrisRackauckas** [comment]
`x` and `y` can still be variables which are looking to be found. These things you're writing down show up in delay differential equations for example, where we are solving for `x`/`y`.

**Comment by jpfairbanks** [comment]
Now I guess I’m confused about the difference between a function and a variable.  What’s the difference?

**Comment by ChrisRackauckas** [comment]
A variable is a function that needs to be replaced in order to form a whole statement. It's a stand-in, but instead of just being a stand-in for finite dimensional values, it can be a stand-in for an infinite dimensional value as well.

**Comment by jpfairbanks** [comment]
So this came up again with @dpsanders in the context of `convert(Expr, ex::Expression)` would it make sense to have a function like `convert(Expr, ex::Expression, d::Dict{Variable, Any)` so that you would replace the variables with the value you wanted (which could be a Symbol) in the conversion?

I have a library that wants to pass `Eqn`s like `V ~ V+1` and create the function `f(x) = x+1`, then call that function to modify the value of `V` like `V = f(V)` One possible API that makes sense is:

```julia
function g()
    @variables V
    ex = V ~ V+1
    f = functionize(ex) # f(x) = x+1
    ex.lhs = f(eval(variables(ex.rhs)))
end

**Comment by jlumpe** [comment]
I've been thinking about this, I feel like it might make sense to consolidate all the variable types and everything into a single "context" object. Currently I think that variables pretty much just have a `known::Bool` field or something? Other than that they're pretty much just plain symbols. It might make it easier to just be able to work with plain Julia symbols and expression trees wherever possible, instead of having to have the correct references to all the variables.

I think this could provide a lot of extensibility, by giving users the ability to make their own specialized context classes and attach whatever information they want to variables without having to extend the variable types and macros themselves (and whatever functions use them). It could also avoid some potential conflicts that I think are possible with regards to function registration (what if a library registers a function under some name, but I want to use that name for a different function?). That could be solved by having the library register functions under its own context and having the user use or derive from that context.

Of course that means you would need to pass around the context object wherever it is needed, including to macros like `@variables` and `@parameters`. I don't know if this is bad design or not, but you could use a global context by default. Then all the functions could have a signature like `myfunc(ctx::Context, expr::Expr, ...)` and then a method like `myfunc(expr::Expr, ...) = myfunc(globalcontext(), expr, ...)` for each. You could use an alternate context with a block of statements with a macro like

```julia
@withcontext myctx begin
    @variables x y z
    ...
end
```
