### ISSUE TITLE
Collecting symbolic array breaks usage of `all` on symbolic arrays

### ISSUE THREAD

**Issue by AayushSabharwal** [SciML/ModelingToolkit.jl#1742]
I'm not sure on how best to phrase this, so the title is a bit weird. Hopefully the MWE explains it:
```julia
julia> @variables p1(t)[1:2] p2(t)[1:2]
julia> (p2 .- p1) .<= SVector{2}(1.0, 0.5)
(broadcast(<=, broadcast(-, p2(t), p1(t)), [1.0, 0.5]))[1:2]
julia> all((p2 .- p1) .<= SVector{2}(1.0, 0.5))
Symbolics._mapreduce(identity, &, broadcast(<=, broadcast(-, p2(t), p1(t)), [1.0, 0.5]), Colon(), (:init => true,))

julia> # however...
julia> SVector{2}(p2 .- p1) .<= SVector{2}(1.0, 0.5)
2-element SVector{2, Num} with indices SOneTo(2):
 (broadcast(-, p2(t), p1(t)))[1] <= 1.0
 (broadcast(-, p2(t), p1(t)))[2] <= 0.5
julia> all(SVector{2}(p2 .- p1) .<= SVector{2}(1.0, 0.5))
ERROR: TypeError: non-boolean (Num) used in boolean context
Stacktrace:
 [1] _all
   @ ./reduce.jl:1161 [inlined]
 [2] _all
   @ ./reducedim.jl:903 [inlined]
 [3] #all#756
   @ ./reducedim.jl:901 [inlined]
 [4] all(a::SVector{2, Num})
   @ Base ./reducedim.jl:901
 [5] top-level scope
   @ REPL[46]:1
```

I'm not sure if this is intended behaviour or not. The `SVector{2}` is to pass to another API which uses `SVector` internally.

**Comment by AayushSabharwal** [comment]
It seems this is also the case if `SVector{2}(p2 .- p1)` is replaced with `Tuple(p2 .- p1)` or anything that collects the broadcast

**Comment by bowenszhu** [comment]
I guess `Symbolics.Arr` is not supposed to be wrapped in another collection when calling collection functions, because otherwise the collection function cannot dispatch the methods defined in [Symbolics.jl/src/array-lib.jl](https://github.com/JuliaSymbolics/Symbolics.jl/blob/c8938466a339125f6bfbace6c021eab494bd270a/src/array-lib.jl).

**Comment by bowenszhu** [comment]
I guess `Symbolics.ArrayOp` of `Symbolics.Arr` is not supposed to be unrolled or collected when calling iterable collection functions that involve boolean context, e.g. `all` and  `any`, because otherwise the function cannot dispatch the methods defined in [Symbolics.jl/src/wrapper-types.jl](https://github.com/JuliaSymbolics/Symbolics.jl/blob/c8938466a339125f6bfbace6c021eab494bd270a/src/wrapper-types.jl). 

It's fine for other collection functions, such as `sum`, `prod`, `unique`, since `+`, `*`, `isequal`, etc. are defined for `Num`.

**Comment by bowenszhu** [comment]
The left part `SVector{2}(p2 .- p1)` in `SVector{2}(p2 .- p1) .<= SVector{2}(1.0, 0.5)` is unnecessary, as `SVector` unrolls `Symbolics.ArrayOp`, which dismisses the delayed-computation property of symbolic arrays.

**Comment by AayushSabharwal** [comment]
That makes sense, thanks.
