### ISSUE TITLE
State of `inputoutput.jl`

### ISSUE THREAD

**Issue by hexaeder** [SciML/ModelingToolkit.jl#2852]
**Question❓**

In the context of a larger project, I am interested in using MTK to model parts of my system. However, I don't want to use it all the way to the solver. I'd like to make use of components, structural simplify and so on but leave some "driving" inputs open in the code gen stage.

Essentially, I want what is implemented `inputoutput.jl`. However, while inline documentation exists, those functions seem to be neither exported nor documented in the documentation.

Will this become part of the stable interface of MTK? Is it "safe" to build more infrastructure on top of those? I don't mind some smaller breakage, and I would be happy to contribute to this part of MTK if I encountered any bugs, but I don't want to build on top of a feature that might get scrapped entirely.

cc @mandywal

**Comment by ChrisRackauckas** [comment]
Sorry a bit behind due to JuliaCon

Inputs and outputs are commonly used throughout the standard library and from that are well-tested. It's safe and public API to use essentially all of this. But, we should make that explicit via export/public and documentation.

@baggepinnen could you take a pass at that? You might be the heaviest user of it right now. It needs a manual page down in the manual section.

**Comment by hexaeder** [comment]
Thanks for the clarification, I'm happy to hear that!
