### ISSUE TITLE
Matrix square root for operations?

### ISSUE THREAD

**Issue by sdwfrost** [SciML/ModelingToolkit.jl#449]
This is probably tricky, but I have some models with matrix square root terms, but `sqrt` is not defined for `Array{Operation,2}`.

**Comment by ChrisRackauckas** [comment]
Not element-wise square root but matrix square root?

**Comment by sdwfrost** [comment]
Element-wise works fine, but yes, matrix square root

**Comment by ChrisRackauckas** [comment]
`sqrt.(A)` would do element-wise square root of a symbolic matrix. For matrix square root, I'm not sure the symbolic solution is generally available for larger than 5x5 matrices. I think you run into an Abel's Theorem issue since you can compute these from the matrix log, and that similarly to matrix exponential requires solving polynomial systems.

BTW, if you were thinking about it for SDEs like https://github.com/epirecipes/sir-julia/blob/master/markdown/sde_stochasticdiffeq/sde_stochasticdiffeq.md , I wanted to comment on there that this tutorial isn't a correct implementation of the Chemical Langevin Equation. It's a square root on the reaction rates, but the stoichiometric terms are supposed to be untouched IIRC (if you want convergence to the Gillespie model). @isaacsas pinging you to double check that (I know it's square root one and not the other).

**Comment by sdwfrost** [comment]
Thanks; for my specific use case, I can use element-wise square root (as the matrix is diagonal), and I can define a `sqrt` function on the `Diagonal` matrix type from `LinearAlgebra` to avoid notation confusion, so I have a workaround for now.

Do you think that [https://github.com/epirecipes/sir-julia/blob/master/markdown/sde_stochasticdiffeq/sde_stochasticdiffeq.md](https://github.com/epirecipes/sir-julia/blob/master/markdown/sde_stochasticdiffeq/sde_stochasticdiffeq.md) is wrong? I'm following eq 2.2 from [this](https://www.sciencedirect.com/science/article/pii/S0025556417303644) (or at least, that was my intention).

**Comment by ChrisRackauckas** [comment]
If the purpose is to have it match the statistics of the jump process in the limit, then https://aip.scitation.org/doi/10.1063/1.481811 demonstrates that the SDE would follow a specific form.

**Comment by isaacsas** [comment]
Yes, stoichiometric coefficients go outside the square root, as in eq 23 of the paper Chris references.

**Comment by isaacsas** [comment]
Isn’t that what’s being done in the tutorial you linked?

**Comment by isaacsas** [comment]
Oh, I guess the `c` is missing in `ifrac`?

**Comment by ChrisRackauckas** [comment]
The stoichiometry is in the sqrt, so it should be `ifrac = sqrt(β/N)*I*S` for example (and the no sqrt on the other part)

**Comment by isaacsas** [comment]
I don’t think you are describing the CLE. I thought the square root is of the entire rate propensity. See eq 23 of Gillespie’s paper. For S + I -> 2I at rate beta the propensity is beta*S*I, which would get a square root. The stoichiometric coefficients are -1 for S and 1 for I.

**Comment by sdwfrost** [comment]
I think that the square root is of the entire rate propensity too. See [https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6002090/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6002090/)

**Comment by ChrisRackauckas** [comment]
Oh I see 🤦

**Comment by isaacsas** [comment]
@sdwfrost yes, that paper looks right to me. The earlier one with the matrix square root doesn’t look right (unless they don’t actually mean the matrix square root).

**Comment by isaacsas** [comment]
The way I remember it is that the argument of the Poisson jump process for number of firings is the (time-integrated) propensity. It doesn’t depend on stoichiometry. The stoichiometric coefficients are outside since they tell you how much the process changes the state by each time it fires. It carries over to the noise term in the CLE, which is just a large-population approximation.

**Comment by sdwfrost** [comment]
The problem I was referring to that requires a matrix square root is this one [https://arxiv.org/abs/2001.05099](https://arxiv.org/abs/2001.05099) (equation 13 in [https://arxiv.org/pdf/2001.05099.pdf](https://arxiv.org/pdf/2001.05099.pdf)), which considers the dynamics of the time-integrated propensity. In this specific case, the matrix is diagonal, so the elementwise and matrix square root are equivalent. Closing this for now...

**Comment by ChrisRackauckas** [comment]
Relevant xref: https://github.com/SciML/ModelingToolkit.jl/issues/405

But yes, in general, I don't think you can do a matrix square root: I think it has to be generally numerical.

**Comment by isaacsas** [comment]
Yeah, we should add LNA. It wouldn’t be hard...

**Comment by ChrisRackauckas** [comment]
Are there higher order approximations as well? Could be interesting if we could just generate them.

**Comment by isaacsas** [comment]
Not that I’ve seen, but I haven’t looked at even the LNA much. The (sometimes) poor long-time approximation properties of even the CLE has made me hesitant to use them.

**Comment by sdwfrost** [comment]
I added a simple (but resuable) example of the LNA [here](https://github.com/epirecipes/sir-julia/blob/master/markdown/lna/lna.md). For inference purposes, the LNA is often used in a piecewise fashion to avoid the long-term approximation problem that @isaacsas notes. I'm trying to put together a nice MTK example based on the Fintzi et al. paper, hence the original issue.
