### ISSUE TITLE
Missing isone(::Num) method?

### ISSUE THREAD

**Issue by david-pl** [SciML/ModelingToolkit.jl#653]
There is no specialized method for `Base.isone(::Num)`, yet there is one for `Base.iszero` leading to this behavior:
```julia
julia> using ModelingToolkit

julia> @parameters p
(p,)

julia> iszero(p)
false

julia> isone(p)
p == 1
```
This is not intended, is it?

**Comment by ChrisRackauckas** [comment]
I think it's because of what's needed to trace. @shashi ?

**Comment by shashi** [comment]
We can definitely add this.

**Comment by YingboMa** [comment]
I am not sure if we want to do that. The reason that we have `iszero` is to handle sparse matrices. Also, since,`p` being exactly zero often means incorrect inputs when there's a `iszero` check in the program, so we want to set `iszero(::Num)` to false. But that's not the case for `isone`. If overloading `isone` actually fixes a concrete problem. I'd be happy to add this overload.

**Comment by david-pl** [comment]
I stumbled over this while playing around with MTK and some custom rules. I wasn't sure whether it was intentional so I filed this issue. If needed such cases could be handled using something like SymbolicUtils `_isone` I suppose. So if you're uncomfortable overloading this feel free to close the issue.
