### ISSUE TITLE
Rename / clarify that this is a CAS?

### ISSUE THREAD

**Issue by StefanKarpinski** [SciML/ModelingToolkit.jl#821]
In https://discourse.julialang.org/t/julia-from-the-perspective-of-a-pythonista/55956/8 @oxinabox makes the point that it’s hard from looking at this package to understand that it has become a fairly general purpose and capable CAS. Would it make sense to “rebrand” with a catchier name or at least make the documentation reflect this better?

**Comment by ChrisRackauckas** [comment]
See the rest of the thread. Symbolics.jl, we're separating out the CAS etc. etc. Should be done this week.

**Comment by StefanKarpinski** [comment]
Could you distill here what the plan is from that very long thread?

**Comment by ChrisRackauckas** [comment]
https://discourse.julialang.org/t/julia-from-the-perspective-of-a-pythonista/55956/17?u=chrisrackauckas

The CAS of MTK is moving to Symbolics.jl by the end of the week. We're just behind on it. SymbolicUtils.jl is a utility package for building symbolic systems, which just defines things like rule-based rewriting systems. Symbolics.jl will get all of the CAS features, like "the definition of a real number" with derivatives and all of that. MTK will be the whole set of AbstractSystems for differential equations, optimization, nonlinear systems, and above. There's not much more to say: it'll make sense when we do it, and the main reason it's not done right now is just because we're busy, so we're just going to get back to work and it'll show up and answer the questions better than an explanation.

**Comment by ChrisRackauckas** [comment]
If you want to help do the split, I can guide you as to what to split, but 🤷 that's the point we're at. Not high level, just get busy with it.

**Comment by StefanKarpinski** [comment]
I do not 🥰

**Comment by ChrisRackauckas** [comment]
Exactly. So we know exactly what we want to do, we should've did it last week, but 🤷 so there's not much of a point in talking about it. You'll see the repo and the docs and will be happy, so... Imma go do it 😆

**Comment by ChrisRackauckas** [comment]
See https://discourse.julialang.org/t/ann-symbolics-jl-a-modern-computer-algebra-system-for-a-modern-language/56251?u=chrisrackauckas .
