### ISSUE TITLE
Variable uniqueness

### ISSUE THREAD

**Issue by HarrisonGrodin** [SciML/ModelingToolkit.jl#89]
Currently, variables are equal exactly when they have the same name/subtype. However, this can be problematic in various cases, with variables created in two different contexts being treated as equal (e.g. first-order transformation).

The most obvious solution would be to treat each variable instance as strictly unique, attaching an ID at creation. At first glance, this doesn't seem conducive to testing when functions create new variables, but it's possible that some workarounds (either internally or in the test suite) could trivially solve this.

**Comment by ChrisRackauckas** [comment]
Yeah, some kind of hash or UUID makes sense, so that even if names collide the computationally still works.

**Comment by jpfairbanks** [comment]
I think the idea of incorporating a *scope* into each variable would make sense if we want variables defined in different contexts to be logically different. Some applications will want "all variables with the same name and type are the same" and some applications will want "variables from different contexts are different" so it seems like picking one or the other will cause problems for somebody. But incorporating a UUID is probably overkill, and it would make testing harder.

If the `StatsModels.@formula` macro were implemented using ModelingToolkit variables and Expressions instead of their current implementation there would be problems. In that case each variable refers to the column of a dataframe, so model selection algorithms will have multiple `Equations` with overlapping sets of variables. Those overlapping sets of variables will probably want the "same name and type are the same" behavior.

The first order transformation use case you mentioned is probably important, what is going on there?

**Comment by ChrisRackauckas** [comment]
Scope is now incorporated into the name which fits the behavior we need.
